tl_content:
  type: Element
  singular: ContentElement
  plural: ContentElements
  resolver: DieSchittigs\ContaoGraphQLBundle\Type\Resolvers\ContentElement
tl_article:
  singular: Article
  plural: Articles
tl_user:
  singular: User
  plural: Users
