services:
  DieSchittigs\ContaoGraphQLBundle\Controller\GraphQLController:
    arguments:
      - '@contao.framework'
      - '@contao.graphql.generator'
  contao.graphql.generator:
    class: DieSchittigs\ContaoGraphQLBundle\Type\ObjectTypeGenerator
    arguments:
      - '@service_container'
  contao.graphql.resolver.default:
    class: DieSchittigs\ContaoGraphQLBundle\Type\Resolvers\Resolver
  contao.graphql.resolver.tl_content:
    class: DieSchittigs\ContaoGraphQLBundle\Type\Resolvers\ContentElement